language: node_js
node_js:
    - "node"
    - "7"
cache:
    directories:
        - "node_modules"
before_install:
  # Force npm version 5.x for node versions before 9.x
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
install:
    - npm install
before_script:
  - greenkeeper-lockfile-update
script:
    - npm test
    - npm run lint
after_script:
    # Only the newest node version job will upload the lockfile
  - greenkeeper-lockfile-upload
